apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../k8s
patches:
  - target:
      kind: PersistentVolumeClaim
      name: qdrant-storage
      namespace: ai-system
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: standard
  - target:
      kind: ConfigMap
      name: rag-api-config
      namespace: ai-system
    patch: |-
      - op: replace
        path: /data/LLM_PROVIDER
        value: mock
      - op: replace
        path: /data/MODEL_NAME
        value: mock
  - target:
      kind: HorizontalPodAutoscaler
      name: rag-api
      namespace: ai-system
    patch: |-
      $patch: delete
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: rag-api
        namespace: ai-system
  - target:
      kind: HorizontalPodAutoscaler
      name: vllm
      namespace: ai-system
    patch: |-
      $patch: delete
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: vllm
        namespace: ai-system
