apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llm-rag-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SecureCloudOps/llm-rag-infra-platform.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
