apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: llm-rag-infra-platform
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: llm-rag-infra-platform
automountServiceAccountToken: false
